[default]
# DEBUG = true
# VERSION = "0.0.1"

DOCS_PATH = "docs/project_docs"
PROJECT_NAME = "project-metrics"
WF_PATH = ".github/workflows/wf.yml"

GITHUB_USERNAME = "TheNewThinkTank"
GITLAB_USERNAME = "TheNewThinkTank"
BITBUCKET_USERNAME = "Gustav_Collin_Rasmussen"

GITHUB_TOKEN = "PROJECT_METRICS_GITHUB_ACCESS_TOKEN"
FINEGRAINED_GITHUB_TOKEN = "FG_GITHUB_ACCESS_TOKEN"
GITLAB_TOKEN = "PROJECT_METRICS_GITLAB_ACCESS_TOKEN"
BITBUCKET_TOKEN = "PROJECT_METRICS_BITBUCKET_ACCESS_TOKEN"

LANGUAGES = [
  "Python",
  "TypeScript",
]

PYTHON_SAMPLE_REPOS = [
  "project-metrics",
  "fitness-tracker",
  "N-body-simulations",
]

ACTIVE_REPOS = [
  "project-metrics",
  "fitness-tracker",
  "biblio-sphere",
]

[default.platforms]

[default.platforms.github]
username = "@jinja {{ this.GITHUB_USERNAME }}"
repos_url = "@jinja https://api.github.com/users/{{ this.GITHUB_USERNAME }}/repos"
api_url = "https://api.github.com/repos/{owner}/{repo}"
access_token = "@jinja {{ this.GITHUB_TOKEN }}"
stars = "stargazers_count"
url = "html_url"

[default.platforms.github.badges]

[default.platforms.github.badges.size_badge]
label = "GitHub repo size"
value = [
  "@jinja https://img.shields.io/github/repo-size/{{ this.GITHUB_USERNAME }}/{repo}?style=flat&logo=github&logoColor=whitesmoke&label=Repo%20Size",
  "@jinja https://github.com/{{ this.GITHUB_USERNAME }}/{repo}/archive/refs/heads/main.zip",
]

[default.platforms.github.badges.ci_badge]
label = "CI"
value = "@jinja https://github.com/{{ this.GITHUB_USERNAME }}/{repo}/actions/workflows/wf.yml/badge.svg"

[default.platforms.github.badges.codecov_badge]
label = "codecov"
value = [
  "@jinja https://codecov.io/gh/{{ this.GITHUB_USERNAME }}/{repo}/branch/main/graph/badge.svg",
  "@jinja https://codecov.io/gh/{{ this.GITHUB_USERNAME }}/{repo})",
]

[default.platforms.gitlab]
username = "@jinja {{ this.GITLAB_USERNAME }}"
repos_url = "@jinja https://gitlab.com/api/v4/users/{{ this.GITLAB_USERNAME }}/projects?owned=true&visibility=public"
api_url = "https://gitlab.com/api/v4/projects/{owner}%2F{repo}"
access_token = "@jinja {{ this.GITLAB_TOKEN }}"
stars = "star_count"
url = "web_url"

# [default.platforms.bitbucket]
# username = "@jinja {{ this.BITBUCKET_USERNAME }}"
# repos_url = "@jinja https://api.bitbucket.org/2.0/repositories/{{ BITBUCKET_USERNAME }}"
# api_url = "https://api.bitbucket.org/2.0/repositories/{owner}/{repo}"
# access_token = "@jinja {{ BITBUCKET_TOKEN }}"
# stars = ""
# url = ""
