[default]
# DEBUG = true
# VERSION = "0.0.1"

DOCS_PATH = "docs/project_docs"
PROJECT_NAME = "project-metrics"
WF_PATH = ".github/workflows/wf.yml"

GITHUB_USERNAME = "TheNewThinkTank"
GITLAB_USERNAME = "TheNewThinkTank"
BITBUCKET_USERNAME = "Gustav_Collin_Rasmussen"

GITHUB_TOKEN = "PROJECT_METRICS_GITHUB_ACCESS_TOKEN"
FINEGRAINED_GITHUB_TOKEN = "FG_GITHUB_ACCESS_TOKEN"
GITLAB_TOKEN = "PROJECT_METRICS_GITLAB_ACCESS_TOKEN"
BITBUCKET_TOKEN = "PROJECT_METRICS_BITBUCKET_ACCESS_TOKEN"

LANGUAGES = [
  "Python",
  "TypeScript",
]

PYTHON_SAMPLE_REPOS = [
  "project-metrics",
  "fitness-tracker",
  "N-body-simulations",
]

ACTIVE_REPOS = [
  "project-metrics",
  "fitness-tracker",
  "biblio-sphere",
]

[platforms]

[platforms.github]
username = "${GITHUB_USERNAME}"
repos_url = "https://api.github.com/users/${GITHUB_USERNAME}/repos"
api_url = "https://api.github.com/repos/{owner}/{repo}"
access_token = "${GITHUB_TOKEN}"
stars = "stargazers_count"
url = "html_url"

[platforms.github.badges]

[platforms.github.badges.size_badge]
label = "GitHub repo size"
value = [
  "https://img.shields.io/github/repo-size/TheNewThinkTank/{repo}?style=flat&logo=github&logoColor=whitesmoke&label=Repo%20Size",
  "https://github.com/TheNewThinkTank/{repo}/archive/refs/heads/main.zip",
]

[platforms.github.badges.ci_badge]
label = "CI"
value = "https://github.com/TheNewThinkTank/{repo}/actions/workflows/wf.yml/badge.svg"

[platforms.github.badges.codecov_badge]
label = "codecov"
value = [
  "https://codecov.io/gh/TheNewThinkTank/{repo}/branch/main/graph/badge.svg",
  "https://codecov.io/gh/TheNewThinkTank/{repo})",
]

[platforms.gitlab]
username = "${GITLAB_USERNAME}"
repos_url = "https://gitlab.com/api/v4/users/${GITLAB_USERNAME}/projects?owned=true&visibility=public"
api_url = "https://gitlab.com/api/v4/projects/{owner}%2F{repo}"
access_token = "${GITLAB_TOKEN}"
stars = "star_count"
url = "web_url"

# [platforms.bitbucket]
# username = "${BITBUCKET_USERNAME}"
# repos_url = "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_USERNAME}"
# api_url = "https://api.bitbucket.org/2.0/repositories/{owner}/{repo}"
# access_token = "${BITBUCKET_TOKEN}"
# stars = ""
# url = ""
