[default]
# DEBUG = true
# VERSION = "0.0.1"

DOCS_PATH = "docs/project_docs"
PROJECT_NAME = "project-metrics"
WF_PATH = ".github/workflows/wf.yml"

GITHUB_USERNAME = "TheNewThinkTank"
GITLAB_USERNAME = "TheNewThinkTank"
BITBUCKET_USERNAME = "Gustav_Collin_Rasmussen"

GITHUB_TOKEN = "PROJECT_METRICS_GITHUB_ACCESS_TOKEN"
FINEGRAINED_GITHUB_TOKEN = "FG_GITHUB_ACCESS_TOKEN"
GITLAB_TOKEN = "PROJECT_METRICS_GITLAB_ACCESS_TOKEN"
BITBUCKET_TOKEN = "PROJECT_METRICS_BITBUCKET_ACCESS_TOKEN"

LANGUAGES = [
  "Python",
  "TypeScript",
]

PYTHON_SAMPLE_REPOS = [
  "project-metrics",
  "fitness-tracker",
  "N-body-simulations",
]

ACTIVE_REPOS = [
  "project-metrics",
  "fitness-tracker",
  "biblio-sphere",
]
