name: Update Repos

on:
  workflow_call:
    inputs:
      PYTHONVERSION:
        required: true
        type: string
    secrets:
      PROJECT_METRICS_GITHUB_ACCESS_TOKEN:
        required: true
      FG_GITHUB_ACCESS_TOKEN:
        required: true

jobs:
  update_repos:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Python and Poetry
        uses: TheNewThinkTank/gh-actions/.github/actions/setup-python-poetry@v1.0.0  # main
        with:
          python-version: ${{ inputs.PYTHONVERSION }}

      # TODO: if repo has tests, setup codecov badge on it's README
      # TODO: if repo has wf, setup CI badge on it's README

      # - name: update repos with README size badge
      #   run: |
      #     poetry run python src/REST/add_badge.py
      #     poetry run python src/REST/threading_add_badge.py

      - name: add GitHub Actions workflow to repos
        run: |
          poetry run python src/threading_add_gha_wf.py
        # poetry run python src/add_gha_wf.py
        env:
          PROJECT_METRICS_GITHUB_ACCESS_TOKEN: ${{ secrets.PROJECT_METRICS_GITHUB_ACCESS_TOKEN }}
