name: Matrix strategy - Update GH repos

on:
  workflow_dispatch:

env:
  PROJECT_METRICS_GITHUB_PAT: ${{ secrets.PROJECT_METRICS_GITHUB_PAT }}
  PROJECT_METRICS_GITHUB_ACCESS_TOKEN: ${{ secrets.PROJECT_METRICS_GITHUB_ACCESS_TOKEN }}
  PYTHONPATH: ${{ github.workspace }}/src
  PYTHONVERSION: 3.12

jobs:
  get_gh_repo_names:
    runs-on: ubuntu-latest

    outputs:
      repos: ${{ steps.repos.outputs.repositories }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHONVERSION }}
          cache: pip

      - name: Install and cache poetry
        run: |
          make install-poetry
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Cache poetry dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: ${{ runner.os }}-poetry-

      - name: Install dependencies with poetry
        run: poetry install
        env:
          POETRY_VIRTUALENVS_IN_PROJECT: true
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Output Configuration
        id: repos
        run: |  # Make sure the delimiter used is randomly generated and unique for each run
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "repositories<<$EOF" >> "$GITHUB_OUTPUT"
          poetry run python src/util/matrix_repos.py >> "$GITHUB_OUTPUT"
          echo "$EOF" >> "$GITHUB_OUTPUT"

      - name: echo repository
        run: echo "${{ steps.repos.outputs.repositories }}"

  update_repos:
    needs:
      - get_gh_repo_names

    runs-on: ubuntu-latest

    strategy:
      matrix:
        repository: ${{ fromJson(needs.get_gh_repo_names.outputs.repos) }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHONVERSION }}
          cache: pip

      - name: Install and cache poetry
        run: |
          make install-poetry
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Cache poetry dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: ${{ runner.os }}-poetry-

      - name: Install dependencies with poetry
        run: poetry install
        env:
          POETRY_VIRTUALENVS_IN_PROJECT: true
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Matrix => (${{ matrix.repository }})
        run: |
          poetry run python src/matrix_add_badge.py --repo_name ${{ matrix.repository }}
