name: Update Repos

on:
  workflow_call:
    inputs:
      PYTHONVERSION:
        required: true
        type: string
    secrets:
      PROJECT_METRICS_GITHUB_ACCESS_TOKEN:
        required: true

jobs:
  update_repos:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.PYTHONVERSION }}
          # cache: pip

      - name: Install and cache poetry
        run: make install-poetry
        # if: steps.cache.outputs.cache-hit != 'true'

      # - name: Cache poetry dependencies
      #   id: cache
      #   uses: actions/cache@v4
      #   with:
      #     path: ~/.cache/pypoetry/virtualenvs
      #     key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
      #     restore-keys: ${{ runner.os }}-poetry-

      - name: Install dependencies with poetry
        run: poetry install
        env:
          POETRY_VIRTUALENVS_IN_PROJECT: true
        # if: steps.cache.outputs.cache-hit != 'true'

      # TODO: if repo has tests, setup codecov badge on it's README
      # TODO: if repo has wf, setup CI badge on it's README

      # - name: update repos with README size badge
      #   run: |
      #     poetry run python src/REST/add_badge.py

      - name: add GitHub Actions workflow to repos
        run: |
          poetry run python src/add_gha_wf.py
