---
name: Project Metrics Workflow

# NB: Only set manual trigger or schedule, as the wf will otherwise recursively keep invoking itself
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

env:
  PYTHONVERSION: 3.12

jobs:

  vars:
    runs-on: ubuntu-latest
    outputs:
      PYTHONVERSION: ${{ env.PYTHONVERSION }}
    steps:
      - run: echo "Exposing env vars"

  qualify_code:
    needs: vars
    uses: ./.github/workflows/job_qualify_code.yml
    with:
      WILY_PATH: "docs/project_docs/code-analysis/"
      PYTHONVERSION: ${{ needs.vars.outputs.PYTHONVERSION }}  # 3.12
    secrets:
      PROJECT_METRICS_GITHUB_ACCESS_TOKEN: ${{ secrets.PROJECT_METRICS_GITHUB_ACCESS_TOKEN }}

  get_metrics:
    needs:
      - qualify_code
    uses: ./.github/workflows/job_get_metrics.yml
    with:
      PYTHONVERSION: 3.12
    secrets:
      PROJECT_METRICS_GITHUB_ACCESS_TOKEN: ${{ secrets.PROJECT_METRICS_GITHUB_ACCESS_TOKEN }}
      FG_GITHUB_ACCESS_TOKEN: ${{ secrets.FG_GITHUB_ACCESS_TOKEN }}

  update_repos:
    needs:
      - get_metrics
    uses: ./.github/workflows/job_update_repos.yml
    with:
      PYTHONVERSION: 3.12
    secrets:
      PROJECT_METRICS_GITHUB_ACCESS_TOKEN: ${{ secrets.PROJECT_METRICS_GITHUB_ACCESS_TOKEN }}
      FG_GITHUB_ACCESS_TOKEN: ${{ secrets.FG_GITHUB_ACCESS_TOKEN }}
