---
name: Project Metrics Workflow

# NB: Only set manual trigger or schedule, as the wf will otherwise recursively keep invoking itself
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:

  # qualify_code:
  #   uses: ./.github/workflows/qualify_code.yml
  #   with:
  #     PYTHONVERSION: 3.12
  #     WILY_PATH: "docs/project_docs/code-analysis/"
  #   secrets:
  #     PROJECT_METRICS_GITHUB_ACCESS_TOKEN: ${{ secrets.PROJECT_METRICS_GITHUB_ACCESS_TOKEN }}

  get_metrics:
    # needs:
    #   - qualify_code
    uses: ./.github/workflows/get_metrics.yml
    with:
      PYTHONVERSION: 3.12
    secrets:
      PROJECT_METRICS_GITHUB_ACCESS_TOKEN: ${{ secrets.PROJECT_METRICS_GITHUB_ACCESS_TOKEN }}

  update_repos:
    needs:
      - get_metrics
    uses: ./.github/workflows/update_repos.yml
    with:
      PYTHONVERSION: 3.12
    secrets:
      PROJECT_METRICS_GITHUB_ACCESS_TOKEN: ${{ secrets.PROJECT_METRICS_GITHUB_ACCESS_TOKEN }}
