---
name: Project Metrics Workflow

on:  # Only set manual trigger, as the wf will otherwise recursively keep invoking itself
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
  # schedule:
  #   - cron:  '0 0 * * *'

env:
  FG_GITHUB_ACCESS_TOKEN: ${{ secrets.FG_GITHUB_ACCESS_TOKEN }}  # General, fine-grained token
  PROJECT_METRICS_GITHUB_ACCESS_TOKEN: ${{ secrets.PROJECT_METRICS_GITHUB_ACCESS_TOKEN }}
  PROJECT_METRICS_GITLAB_ACCESS_TOKEN: ${{ secrets.PROJECT_METRICS_GITLAB_ACCESS_TOKEN }}
  # PROJECT_METRICS_BITBUCKET_ACCESS_TOKEN: ${{ secrets.PROJECT_METRICS_BITBUCKET_ACCESS_TOKEN }}

jobs:
  Qualify-Code:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: pip

      - name: Install poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: poetry install
        run: poetry install

      # - name: Cache poetry dependencies
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/.cache/pypoetry/virtualenvs
      #     key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
      #     restore-keys: ${{ runner.os }}-poetry-

      - name: Run unit tests and make coverage report
        run: poetry run pytest --cov=./ --cov-report xml:cov.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./cov.xml
          verbose: true

  Get-Metrics:
    needs:
      - Qualify-Code
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: pip

      - name: Install poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
  
      - name: poetry install
        run: poetry install

      # - name: Cache poetry dependencies
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/.cache/pypoetry/virtualenvs
      #     key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
      #     restore-keys: ${{ runner.os }}-poetry-
  
      - name: Install Dependencies
        run: poetry install

      # - name: GitHub GraphQL largest repos
      #   run: |
      #       poetry run python src/gh_graphql_get_largest_repos.py

      # TODO: repos have tests (true/false, grouped. e.g. test or tests folder exist and contains at least 1 non-empty file)
      # TODO: if repo has tests, setup codecov badge on it's README

      # TODO: repos have GH Actions wf (true/false, grouped. e.g. .github/workflows/ exist and contains at least 1 non-empty yaml/yml file)
      # TODO: if repo has tests, setup CI badge on it's README

      - name: REST repos missing description
        env:
          PYTHONPATH: ${{ github.workspace }}/src
        run: |
          poetry run python src/REST/project_metrics.py

      - name: GH GraphQL most popular repos
        env:
          PYTHONPATH: ${{ github.workspace }}/src
        run: |
          poetry run python src/GraphQL/gh_get_popular_repos.py

      - name: GH GraphQL repos by lang
        env:
          PYTHONPATH: ${{ github.workspace }}/src
        run: |
          poetry run python src/GraphQL/gh_group_by_lang.py

      - name: update repos
        run: |
          poetry run python src/REST/add_repo_size_badge.py
